metadata:
  name: ${project.artifactId}
data:
  application.properties: |
    # spring application properties file
    welcome = Hello from Kubernetes ConfigMap!!!
    dummy = some value
    spring.data.mongodb.uri=mongodb://mongodb-0.mongodb.default-production.svc.cluster.local:27017,mongodb-1.mongodb.default-production.svc.cluster.local:27017,mongodb-2.mongodb.default-production.svc.cluster.local:27017,mongodb-3.mongodb.default-production.svc.cluster.local:27017/troy?replcaSet=troy

